
FROM node:18

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Installation d'Expo CLI globalement
RUN npm install -g @expo/cli

# Copie du code source
COPY . .

# Exposition du port pour le serveur de développement
EXPOSE 19000
EXPOSE 19001
EXPOSE 19002

# Variables d'environnement pour Expo
ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

# Commande de démarrage
CMD ["npm", "start"]
