version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: travel_paradise
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/travel_paradise
    volumes:
      - ./backend:/var/www/html
    networks:
      - travel_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: http://backend:8000/api
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - travel_network

volumes:
  postgres_data:

networks:
  travel_network:
    driver: bridge
