
version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: travel_paradise
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/travel_paradise
    volumes:
      - ./backend:/var/www/html

  frontend:
    build: ./frontend
    ports:
      - "19000:19000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
