FROM node:18

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Copie du code source
COPY . .

# Exposition du port pour le serveur de développement
EXPOSE 3000

# Variables d'environnement
ENV NODE_ENV=development

# Commande de démarrage
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
