WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port 3000 pour Vite
EXPOSE 3000

# Démarrer l'application React avec Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]