
version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: travel_paradise
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/travel_paradise
    volumes:
      - ./backend:/var/www/html
    networks:
      - travel_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:19000"   # Port web principal changé de 19000 à 3000
      - "3001:19001"   # Port dev tools changé de 19001 à 3001
      - "3002:19002"   # Port metro bundler changé de 19002 à 3002
    depends_on:
      - backend
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - API_BASE_URL=http://backend:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - travel_network

volumes:
  postgres_data:

networks:
  travel_network:
    driver: bridge
